import type { MissionsPageData } from "@/features/missions/listTypes";

export const DEMO_MISSIONS_LIST_DATA: MissionsPageData = {
  sourceBadge: "Placeholder data",
  title: "Missions",
  description: "Review work that needs attention, resume unfinished planning, and follow active or completed missions.",
  freshness: "Placeholder mission records · Updated 13 July 2026 at 08:10 WIB",
  primaryAction: { label: "New mission", href: "/missions/new" },
  overview: [
    { id: "attention", label: "Needs attention", description: "Clarification or approval required", statuses: ["awaiting-clarification", "awaiting-approval"] },
    { id: "active", label: "Active", description: "Approved work in progress", statuses: ["active"] },
    { id: "draft", label: "Drafts", description: "Saved requests not yet planned", statuses: ["draft"] },
    { id: "closed", label: "Closed", description: "Completed mission records", statuses: ["closed"] },
  ],
  filters: [
    { id: "all", label: "All", statuses: ["draft", "awaiting-clarification", "awaiting-approval", "active", "closed"] },
    { id: "attention", label: "Needs attention", statuses: ["awaiting-clarification", "awaiting-approval"] },
    { id: "active", label: "Active", statuses: ["active"] },
    { id: "draft", label: "Drafts", statuses: ["draft"] },
    { id: "closed", label: "Closed", statuses: ["closed"] },
  ],
  missions: [
    {
      id: "mission-east-chili-harvest",
      title: "Harvest East Block chili",
      description: "Protect saleable market-quality A quantity for the buyer commitment before the estimated rain window.",
      status: "awaiting-approval",
      statusLabel: "Awaiting approval",
      statusTone: "warning",
      risk: "high",
      riskLabel: "Deadline and rain risk",
      context: [
        { id: "crop", label: "Crop / block", value: "Chili · East Block" },
        { id: "commitment", label: "Buyer commitment", value: "80 kg · Market quality A" },
        { id: "constraint", label: "Main constraint", value: "Rain estimated before noon" },
      ],
      deadline: { label: "Tomorrow · 14:00 WIB", dateTime: "2026-07-13T14:00:00+07:00" },
      updated: { label: "Updated 12 minutes ago", dateTime: "2026-07-13T07:58:00+07:00" },
      action: { label: "Review mission", href: "/missions/new" },
    },
    {
      id: "mission-shallot-drying",
      title: "Plan shallot drying after harvest",
      description: "Choose a drying window and handling approach without assuming weather or capacity that has not been provided.",
      status: "awaiting-clarification",
      statusLabel: "Awaiting clarification",
      statusTone: "info",
      risk: "unknown",
      riskLabel: "Risk requires clarification",
      context: [
        { id: "crop", label: "Crop / batch", value: "Shallot · Batch SH-04" },
        { id: "missing", label: "Missing context", value: "Harvest amount and drying conditions" },
      ],
      updated: { label: "Updated yesterday", dateTime: "2026-07-12T16:20:00+07:00" },
      unavailableActionLabel: "Resume route coming next",
    },
    {
      id: "mission-chili-cycle",
      title: "Develop the next two-month chili cycle",
      description: "Draft a longer mission for crop establishment, growing conditions, milestones, and the desired harvest outcome.",
      status: "draft",
      statusLabel: "Draft",
      statusTone: "neutral",
      risk: "unknown",
      riskLabel: "Not assessed",
      context: [
        { id: "crop", label: "Crop", value: "Chili" },
        { id: "duration", label: "Planning horizon", value: "Two months" },
      ],
      updated: { label: "Updated 2 days ago", dateTime: "2026-07-11T10:05:00+07:00" },
      unavailableActionLabel: "Resume route coming next",
    },
    {
      id: "mission-drainage-recovery",
      title: "Stabilize drainage after heavy rain",
      description: "Monitor field conditions and complete approved recovery steps before reassessing the crop batch.",
      status: "active",
      statusLabel: "Active",
      statusTone: "ai",
      risk: "medium",
      riskLabel: "Medium field risk",
      context: [
        { id: "block", label: "Field block", value: "North Block" },
        { id: "progress", label: "Progress", value: "2 of 5 steps completed" },
      ],
      deadline: { label: "Today · 17:00 WIB", dateTime: "2026-07-13T17:00:00+07:00" },
      updated: { label: "Updated 34 minutes ago", dateTime: "2026-07-13T07:36:00+07:00" },
      action: { label: "Open mission", href: "/missions/mission-drainage-recovery" },
    },
    {
      id: "mission-tomato-market-trial",
      title: "Close tomato market-quality trial",
      description: "Record the final outcome and review the difference between expected and actual saleable quantity.",
      status: "closed",
      statusLabel: "Closed",
      statusTone: "success",
      risk: "low",
      riskLabel: "Closed without active risk",
      context: [
        { id: "crop", label: "Crop / batch", value: "Tomato · Trial TM-02" },
        { id: "outcome", label: "Recorded outcome", value: "42 kg saleable" },
      ],
      updated: { label: "Closed 6 days ago", dateTime: "2026-07-07T15:40:00+07:00" },
      action: { label: "Review mission", href: "/outcomes/mission-tomato-market-trial" },
    },
  ],
  emptyState: {
    title: "No missions match this filter",
    description: "Choose another status or create a new mission.",
  },
  assistant: {
    contextLabel: "Mission list loaded",
    starterMessage: "Ask me which missions need attention, what is active, or where to resume planning.",
    inputPlaceholder: "Ask about your missions…",
    responses: [
      { id: "attention", keywords: ["attention", "urgent", "priority", "first"], text: "Two placeholder missions need attention. Harvest East Block chili is awaiting approval and has high deadline and rain risk, so it should be reviewed first. The shallot drying mission still needs clarification." },
      { id: "active", keywords: ["active", "progress", "running"], text: "One placeholder mission is active: Stabilize drainage after heavy rain. It has completed 2 of 5 steps and currently has medium field risk." },
      { id: "draft", keywords: ["draft", "resume", "unfinished"], text: "The two-month chili cycle is saved as a draft. You can resume it through the current New Mission demonstration while durable mission-detail routes are still being built." },
      { id: "closed", keywords: ["closed", "complete", "outcome"], text: "One placeholder mission is closed: the tomato market-quality trial, with 42 kg recorded as saleable. Detailed outcome comparison is planned for a later screen." },
    ],
    fallbackResponse: "This placeholder list contains five missions: two need attention, one is active, one is a draft, and one is closed. Ask about a status or which mission to review first.",
  },
};
