import { useEffect, useRef, useState } from "react";
import { Bot, ClipboardList, Sparkles, X } from "lucide-react";
import { actOnTunasMessage, checkTunasForecast, createTunasTestAlert, getTunasMessages, markTunasRead, type TunasAction, type TunasMessage, type TunasState } from "@/api/tunas";
import { Button } from "@/components/ui/Button";
import { ChatBubble } from "@/components/ui/ChatBubble";
import { Link, useNavigate } from "react-router";

const empty: TunasState = { messages: [], unreadCount: 0 };

export function TunasAssistant() {
  const navigate = useNavigate();
  const [open, setOpen] = useState(false); const [state, setState] = useState<TunasState>(empty); const [loading, setLoading] = useState(true); const [working, setWorking] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { let live = true; void Promise.all([getTunasMessages(), checkTunasForecast()]).then(([, result]) => { if (live) setState(result); }).catch((reason) => { if (live) setError(reason instanceof Error ? reason.message : "Tunas AI could not load."); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, []);
  useEffect(() => { if (open) scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight }); }, [open, state.messages]);
  async function show() { setOpen(true); try { setState(await markTunasRead()); } catch { /* History stays available if marking read fails. */ } }
  async function test(scenario: "drying-rain" | "harvest-rain" | "irregular-rain") { setWorking(scenario); setError(null); try { setState(await createTunasTestAlert(scenario)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not generate the demo alert."); } finally { setWorking(null); } }
  async function act(message: TunasMessage, item: TunasAction) { setWorking(`${message.tunasMessageId}:${item.id}`); setError(null); try { const result = await actOnTunasMessage(message.tunasMessageId, item.id); setState(result.messages); if (result.navigation) navigate(`/missions/${result.navigation.missionId}/edit`, { state: { tunasDraft: result.navigation.draft, tunasAutoGenerate: result.navigation.autoGenerate } }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save that decision."); } finally { setWorking(null); } }
  return <div className="fixed bottom-[calc(env(safe-area-inset-bottom)+5rem)] right-3 z-40 sm:bottom-5 sm:right-5 lg:bottom-6 lg:right-6">
    {open ? <section aria-label="Tunas AI" className="motion-enter flex h-[min(620px,calc(100dvh-7rem))] w-[min(390px,calc(100vw-1.5rem))] flex-col overflow-hidden rounded-xl border border-ai-100 bg-card shadow-lift" onKeyDown={(event) => { if (event.key === "Escape") setOpen(false); }}>
      <header className="flex items-center justify-between gap-3 bg-ai-700 px-4 py-3 text-white"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-white/15"><Bot className="h-5 w-5" aria-hidden="true" /></span><div><h2 className="font-bold">Tunas AI</h2><p className="text-xs text-white/80">Weather-aware mission support</p></div></div><Button type="button" size="icon" variant="ghost" className="border-transparent text-white hover:bg-white/15 hover:text-white" aria-label="Close Tunas AI" onClick={() => setOpen(false)}><X aria-hidden="true" /></Button></header>
      <div ref={scrollRef} className="flex-1 space-y-3 overflow-y-auto p-4" aria-live="polite" aria-busy={loading}>{loading ? <p className="text-sm text-muted-foreground">Checking your mission forecast…</p> : state.messages.length ? state.messages.map((message) => <div key={message.tunasMessageId} className="grid gap-2"><ChatBubble variant={message.role === "farmer" ? "user" : "assistant"}>{message.content}</ChatBubble>{message.mission ? <Link to={`/missions/${message.mission.missionId}`} aria-label={`View related mission: ${message.mission.originalMessage}`} className="grid gap-1 rounded-md border border-ai-100 bg-ai-50 px-3 py-2 text-left text-sm transition-colors hover:bg-ai-100 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/30"><span className="flex items-center gap-2 font-bold text-ai-700"><ClipboardList className="h-4 w-4" aria-hidden="true" />Related mission</span><span className="truncate font-medium text-foreground">{message.mission.originalMessage}</span><span className="text-xs text-muted-foreground">{message.mission.status} · {message.mission.stage}</span></Link> : null}{message.actions.length ? <div className="flex flex-wrap gap-2">{message.actions.map((item) => <Button key={item.id} type="button" size="sm" variant={item.id === "keep" ? "outline" : "primary"} disabled={working !== null} isLoading={working === `${message.tunasMessageId}:${item.id}`} loadingLabel="Saving" onClick={() => void act(message, item)}>{item.label}</Button>)}</div> : null}</div>) : <p className="rounded-md border border-dashed p-4 text-sm leading-6 text-muted-foreground">No weather risks need action right now. Tunas will check active missions again tomorrow.</p>}{error ? <p className="rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive" role="alert">{error}</p> : null}</div>
      <footer className="border-t bg-muted/30 p-3"><p className="mb-2 text-xs font-bold text-muted-foreground">Test Tunas alerts</p><div className="grid grid-cols-3 gap-2"><Button type="button" size="sm" variant="outline" disabled={working !== null} onClick={() => void test("drying-rain")}>Drying rain</Button><Button type="button" size="sm" variant="outline" disabled={working !== null} onClick={() => void test("harvest-rain")}>Harvest rain</Button><Button type="button" size="sm" variant="outline" disabled={working !== null} onClick={() => void test("irregular-rain")}>Irregular rain</Button></div></footer>
    </section> : <Button type="button" size="lg" className="relative min-h-11 rounded-full border-ai-700 bg-ai-700 px-5 text-white shadow-lift hover:bg-ai-700/90" aria-label={`Open Tunas AI${state.unreadCount ? `, ${state.unreadCount} unread alerts` : ""}`} aria-expanded="false" onClick={() => void show()} icon={<Sparkles aria-hidden="true" />}>Tunas AI{state.unreadCount ? <span className="absolute -right-1 -top-1 grid min-h-5 min-w-5 place-items-center rounded-full bg-risk-700 px-1 text-xs font-bold text-white" aria-hidden="true">{state.unreadCount > 9 ? "9+" : state.unreadCount}</span> : null}</Button>}
  </div>;
}
