/**
 * Raw placeholder transport payload. A backend adapter can replace this source
 * without changing the normalized Farm page contract consumed by the UI.
 */
export const FARM_FIXTURE_SOURCE: unknown = {
  sourceLabel: "Placeholder farm data",
  title: "Field blocks",
  description: "Open a field block to review its shallot batches, farmer-reported readiness, observations, buyer commitments, and linked harvest mission.",
  freshness: "Updated 14 July 2026 at 08:15 WIB - Placeholder data",
  farm: {
    name: "Sari Tani Farm",
    location: "Lembang, West Java",
    timezone: "Asia/Jakarta (WIB)",
    notes: "Placeholder shallot-harvest farm. Values on this page are not connected to a real account.",
  },
  blocks: [
    {
      id: "north-block",
      name: "North Block",
      location: "Lembang, West Java",
      areaLabel: "0.8 ha",
      conditionLabel: "Drainage recheck due",
      conditionTone: "warning",
      accessNotes: "Vehicle access from the north service lane.",
      drainageNotes: "Standing water was reported after heavy rain; recheck before harvest work.",
      notes: "Harvest-ready shallots are present. Drainage recovery is active.",
      sourceLabel: "Placeholder farm record",
    },
    {
      id: "east-block",
      name: "East Block",
      location: "Lembang, West Java",
      areaLabel: "0.6 ha",
      conditionLabel: "Readiness reported",
      conditionTone: "success",
      accessNotes: "Hand-cart access from the central path.",
      drainageNotes: "Raised rows and side channels were reported clear.",
      notes: "A buyer target is waiting for farmer-approved harvest planning.",
      sourceLabel: "Placeholder farm record",
    },
    {
      id: "south-bed",
      name: "South Raised Beds",
      location: "Lembang, West Java",
      areaLabel: "0.3 ha",
      conditionLabel: "Setup in progress",
      conditionTone: "info",
      accessNotes: "Walkway access only while the bed edges settle.",
      drainageNotes: "Covered drainage channel is available along the west edge.",
      notes: "A newly planted shallot batch is being tracked as farm context only.",
      sourceLabel: "Placeholder farm record",
    },
  ],
  batches: [
    {
      id: "batch-nb-sh-26",
      crop: "Shallot",
      batchLabel: "NB-SH-26",
      variety: "Bima Brebes",
      blockId: "north-block",
      plantedLabel: "Planted 10 April 2026",
      stage: "Harvest-ready",
      readinessLabel: "Farmer reported: ready",
      statusLabel: "Active",
      notes: "Inspect drainage again before moving the harvest team into the block.",
      sourceLabel: "Placeholder crop batch",
      mission: {
        id: "mission-drainage-recovery",
        title: "Stabilize North Block drainage before harvest",
        statusLabel: "Active",
        statusTone: "ai",
        href: "/missions/mission-drainage-recovery",
      },
    },
    {
      id: "batch-eb-sh-27",
      crop: "Shallot",
      batchLabel: "EB-SH-27",
      variety: "Tajuk",
      blockId: "east-block",
      plantedLabel: "Planted 18 April 2026",
      stage: "Near harvest",
      readinessLabel: "Farmer reported: almost ready",
      statusLabel: "Active",
      notes: "Buyer quantity can be considered only after the farmer confirms readiness.",
      sourceLabel: "Placeholder crop batch",
    },
    {
      id: "batch-sb-sh-28",
      crop: "Shallot",
      batchLabel: "SB-SH-28",
      variety: "Bima Brebes",
      blockId: "south-bed",
      plantedLabel: "Planted 2 July 2026",
      stage: "Early growth",
      readinessLabel: "Farmer reported: not ready",
      statusLabel: "Active",
      notes: "Keep as farm context only; it is not eligible for a harvest mission.",
      sourceLabel: "Placeholder crop batch",
    },
  ],
  observations: [
    {
      id: "observation-water",
      blockId: "north-block",
      title: "Standing water reported",
      detail: "Water remained near the secondary channel after overnight rain. Recheck is required before the harvest plan changes.",
      observedAt: "2026-07-14T07:10:00+07:00",
      observedLabel: "14 July - 07:10 WIB",
      sourceLabel: "Farmer reported",
    },
    {
      id: "observation-readiness",
      blockId: "east-block",
      title: "Leaf fall and bulb condition reported",
      detail: "The farmer reported that the batch is almost ready. This is not an automated readiness decision.",
      observedAt: "2026-07-13T16:40:00+07:00",
      observedLabel: "13 July - 16:40 WIB",
      sourceLabel: "Farmer reported",
    },
  ],
  commitments: [
    {
      id: "commitment-east-shallot",
      blockId: "east-block",
      batchId: "batch-eb-sh-27",
      buyerName: "Lembang Produce Collector",
      crop: "Shallot - EB-SH-27",
      amountLabel: "500 kg",
      marketQuality: "Market quality A",
      dueAt: "2026-07-18T14:00:00+07:00",
      dueLabel: "18 July - 14:00 WIB",
      statusLabel: "Mission not yet approved",
      statusTone: "warning",
    },
  ],
  assistant: {
    contextLabel: "Farm fields loaded",
    starterMessage: "Ask about field blocks, shallot batches, farmer-reported readiness, observations, or buyer commitments for this placeholder farm.",
    responses: [
      { id: "blocks", keywords: ["block", "field", "area"], text: "This placeholder farm has three shallot field blocks. North Block needs a drainage recheck, East Block is almost ready according to the farmer, and South Raised Beds is in early growth." },
      { id: "batches", keywords: ["batch", "crop", "plant", "shallot"], text: "North Block batch NB-SH-26 is farmer-reported ready, East Block batch EB-SH-27 is almost ready, and South Raised Beds batch SB-SH-28 is not ready. Readiness remains farmer-reported." },
      { id: "observation", keywords: ["observation", "water", "condition"], text: "The newest placeholder observation reports standing water in North Block. Recheck it before the approved harvest plan is changed." },
      { id: "buyer", keywords: ["buyer", "commitment", "500", "quality"], text: "The open buyer commitment requests 500 kg of market-quality A shallots from East Block by 18 July at 14:00 WIB. A mission still requires farmer approval." },
    ],
    fallbackResponse: "This farm contains three field blocks, three shallot batches, two observations, and one buyer commitment. Missions use only the records relevant to their goal; none of this demo data is connected to a backend.",
  },
};
