import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowLeft, CalendarDays, CheckCircle2, Circle, ClipboardCheck, ClipboardList, CloudRain, Clock3, FilePlus2, Play, ShieldAlert, Sprout } from "lucide-react";
import { Link } from "react-router";
import type { Mission, MissionCloseoutInput, MissionStage, MissionStep } from "@/api/missions";
import { createTunasTestAlert, getTunasMissionReports, getTunasMissionTimeline, type OperationalReportRecord, type OperationalReportType, type TunasMissionTimeline } from "@/api/tunas";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/Card";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/PageHeader";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { formatStepSchedule, missionPlan, StageBadge, StatusBadge } from "./MissionsView";
import { OperationalReportDialog } from "./OperationalReportDialog";
import { ReportSummary } from "./ReportSummary";

type AdvanceStage = "HARVESTING" | "DRYING" | "FINISHED" | "TO_REVIEW";
type Props = { mission: Mission; onDelete: () => void; deleting: boolean; action: string | null; onAdvance: (stage: AdvanceStage) => void; onSaveCloseout: (values: MissionCloseoutInput) => void; onConfirmCloseout: () => void; onReportApproved: () => void };

export function MissionDetailView({ mission, onDelete, deleting, action, onAdvance, onSaveCloseout, onConfirmCloseout, onReportApproved }: Props) {
  const plan = missionPlan(mission);
  const batches = mission.cropBatches.map((item) => item.cropBatch.variety || "Shallot batch");
  const latestChange = [...mission.messages].reverse().find((message) => message.role === "farmer" && message.content !== mission.originalMessage);
  const currentStep = ["HARVESTING", "DRYING"].includes(mission.stage) ? mission.missionSteps.find((step) => step.stage === mission.stage && step.status !== "COMPLETED") : undefined;
  const [closeoutOpen, setCloseoutOpen] = useState(mission.status === "CLOSEOUT");
  const [timeline, setTimeline] = useState<TunasMissionTimeline | null>(null);
  const [timelineLoading, setTimelineLoading] = useState(true);
  const [timelineError, setTimelineError] = useState<string | null>(null);
  const [reports, setReports] = useState<OperationalReportRecord[]>([]);
  const [reportsLoading, setReportsLoading] = useState(true);
  const [reportsError, setReportsError] = useState<string | null>(null);
  const [reportOpen, setReportOpen] = useState(false);
  const [initialReportType, setInitialReportType] = useState<OperationalReportType>("GENERAL_OPERATIONAL_NOTE");
  const [rainDemoBusy, setRainDemoBusy] = useState(false);
  const [rainDemoNotice, setRainDemoNotice] = useState<string | null>(null);
  const [rainDemoError, setRainDemoError] = useState<string | null>(null);
  const historyRequest = useRef(0);
  const loadOperationalHistory = useCallback(() => {
    const request = ++historyRequest.current;
    setTimelineLoading(true); setReportsLoading(true); setTimelineError(null); setReportsError(null);
    void Promise.allSettled([getTunasMissionTimeline(mission.missionId), getTunasMissionReports(mission.missionId)]).then(([nextTimeline, nextReports]) => {
      if (request !== historyRequest.current) return;
      if (nextTimeline.status === "fulfilled") setTimeline(nextTimeline.value); else setTimelineError(nextTimeline.reason instanceof Error ? nextTimeline.reason.message : "We could not load the operational timeline.");
      if (nextReports.status === "fulfilled") setReports(nextReports.value.reports); else setReportsError(nextReports.reason instanceof Error ? nextReports.reason.message : "We could not load operational reports.");
      setTimelineLoading(false); setReportsLoading(false);
    });
  }, [mission.missionId]);
  const openReport = (type: OperationalReportType = "GENERAL_OPERATIONAL_NOTE") => { setInitialReportType(type); setReportOpen(true); };
  const reportApproved = () => { loadOperationalHistory(); onReportApproved(); };
  async function sendRainDemo() { setRainDemoBusy(true); setRainDemoError(null); setRainDemoNotice(null); try { await createTunasTestAlert(mission.missionId, "harvest-rain"); setRainDemoNotice("Prakiraan demo diproses dan peringatan dikirim ke Telegram."); } catch (reason) { setRainDemoError(reason instanceof Error ? reason.message : "Simulasi prakiraan gagal diproses."); } finally { setRainDemoBusy(false); } }
  useEffect(() => { setCloseoutOpen(mission.status === "CLOSEOUT"); }, [mission.status]);
  useEffect(() => { loadOperationalHistory(); }, [loadOperationalHistory]);
  const headerActionClass = "border-white bg-white text-primary hover:bg-white/90 hover:text-primary focus-visible:ring-white/60 focus-visible:ring-offset-primary";
  return <div className="grid gap-6"><PageHeader navigation={<Link to="/missions" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-white/85 transition-colors hover:text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/60 focus-visible:ring-offset-2 focus-visible:ring-offset-primary"><ArrowLeft className="h-4 w-4" aria-hidden="true" />All missions</Link>} title="Harvest mission" description={mission.originalMessage} badges={<><StatusBadge status={mission.status} />{mission.stage !== "COMPLETED" ? <StageBadge stage={mission.stage} /> : null}</>} actions={<div className="flex w-full flex-col gap-2 sm:w-auto">{mission.status === "ACTIVE" ? <Button type="button" variant="outline" className={headerActionClass} icon={<FilePlus2 aria-hidden="true" />} onClick={() => openReport()}>Report change</Button> : null}{mission.closeout ? <Button type="button" variant="outline" className={headerActionClass} icon={<ClipboardCheck aria-hidden="true" />} onClick={() => setCloseoutOpen(true)}>View closeout</Button> : null}</div>} />
    <div className="grid gap-6"><LifecycleCard mission={mission} currentStep={currentStep} action={action} onAdvance={onAdvance} onReport={openReport} onOpenCloseout={() => setCloseoutOpen(true)} />
      <Card><CardHeader><div className="flex items-center gap-2 text-ai-700"><CloudRain aria-hidden="true" /><CardTitle>Demo peringatan hujan</CardTitle></div><CardDescription>Masukkan prakiraan hujan simulasi, proses dampaknya, lalu kirim peringatan ke Telegram. Simulasi tidak mengubah jadwal.</CardDescription></CardHeader><CardContent className="grid gap-3"><Button type="button" className="w-full sm:w-fit" disabled={mission.status !== "ACTIVE" || rainDemoBusy} isLoading={rainDemoBusy} loadingLabel="Memproses prakiraan" onClick={() => void sendRainDemo()} icon={<CloudRain aria-hidden="true" />}>Simulasikan prakiraan hujan</Button>{mission.status !== "ACTIVE" ? <p className="text-sm text-muted-foreground">Demo hanya tersedia untuk misi aktif.</p> : null}{rainDemoNotice ? <p className="rounded-md border border-leaf-300 bg-leaf-100/50 p-3 text-sm font-semibold text-leaf-700" role="status">{rainDemoNotice}</p> : null}{rainDemoError ? <p className="rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive" role="alert">{rainDemoError}</p> : null}</CardContent></Card>
      <Card><CardHeader><CardTitle>Mission context</CardTitle><CardDescription>Farmer request and crop batches included in this mission.</CardDescription></CardHeader><CardContent className="grid gap-4"><div><p className="text-sm font-semibold text-muted-foreground">Farmer request</p><p className="mt-1 leading-7">{mission.originalMessage}</p></div>{latestChange ? <div className="border-t pt-4"><p className="text-sm font-semibold text-muted-foreground">Latest change reported</p><p className="mt-1 leading-7">{latestChange.content}</p></div> : null}{batches.length ? <div className="border-t pt-4"><p className="text-sm font-semibold text-muted-foreground">Crop batches</p><div className="mt-2 flex flex-wrap gap-2">{batches.map((batch, index) => <Badge key={`${batch}-${index}`} variant="source"><Sprout aria-hidden="true" />{batch}</Badge>)}</div></div> : null}{mission.notes ? <div className="border-t pt-4"><p className="text-sm font-semibold text-muted-foreground">Notes</p><p className="mt-1 leading-7">{mission.notes}</p></div> : null}</CardContent></Card>
      {plan ? <PlanCard plan={plan} /> : null}
      <ScheduleCard steps={mission.missionSteps} currentStepId={currentStep?.missionStepId} />
      <RecentReports reports={reports} loading={reportsLoading} error={reportsError} onRetry={loadOperationalHistory} />
      <TimelineCard timeline={timeline} loading={timelineLoading} error={timelineError} onRetry={loadOperationalHistory} />
      <DangerZone deleting={deleting} onDelete={onDelete} />
    </div><OperationalReportDialog mission={mission} open={reportOpen} initialType={initialReportType} onOpenChange={setReportOpen} onApproved={reportApproved} /><Dialog open={closeoutOpen} onOpenChange={setCloseoutOpen}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{mission.closeout ? "Review closeout" : "Close out this mission"}</DialogTitle><DialogDescription>{mission.closeout ? "Review the recorded outcome before completing the mission." : "Compare the planned outcome with what happened in the field."}</DialogDescription></DialogHeader>{mission.closeout ? <CloseoutCard mission={mission} confirming={action === "confirm-closeout"} onConfirm={onConfirmCloseout} /> : <CloseoutForm mission={mission} saving={action === "closeout"} onSave={onSaveCloseout} />}</DialogContent></Dialog></div>;
}

function RecentReports({ reports, loading, error, onRetry }: { reports: OperationalReportRecord[]; loading: boolean; error: string | null; onRetry: () => void }) { return <Card><CardHeader><CardTitle>Recent accepted reports</CardTitle><CardDescription>Approved field updates used as mission evidence.</CardDescription></CardHeader><CardContent>{loading ? <p className="text-sm text-muted-foreground">Loading reports…</p> : error ? <div className="rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive" role="alert"><p>{error}</p><Button type="button" size="sm" variant="outline" className="mt-3" onClick={onRetry}>Retry reports</Button></div> : reports.length ? <ol className="grid gap-3">{reports.slice(0, 5).map((report) => <li key={report.operationalReportId} className="rounded-md border p-4"><div className="flex justify-end"><Badge variant="success">Accepted</Badge></div><ReportSummary report={report} /></li>)}</ol> : <p className="rounded-md border border-dashed p-4 text-sm text-muted-foreground">No accepted operational reports yet.</p>}</CardContent></Card>; }

function TimelineCard({ timeline, loading, error, onRetry }: { timeline: TunasMissionTimeline | null; loading: boolean; error: string | null; onRetry: () => void }) {
  return <Card><CardHeader><CardTitle>Operational timeline</CardTitle><CardDescription>Recorded mission decisions and changes, newest first.</CardDescription></CardHeader><CardContent>{loading ? <p className="text-sm text-muted-foreground" role="status">Loading operational timeline…</p> : error ? <div className="rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive" role="alert"><p>{error}</p><Button type="button" size="sm" variant="outline" className="mt-3" onClick={onRetry}>Retry timeline</Button></div> : timeline?.events.length ? <ol className="grid gap-3">{[...timeline.events].reverse().map((event) => <li key={event.operationalEventId} className="grid gap-2 rounded-md border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-bold">{eventLabel(event.type)}</p><time className="flex items-center gap-1.5 text-xs text-muted-foreground" dateTime={event.createdAt}><Clock3 className="h-3.5 w-3.5" aria-hidden="true" />{new Date(event.createdAt).toLocaleString("en-ID")}</time></div><p className="text-sm text-muted-foreground">{event.actor} via {event.channel}</p>{event.before !== null || event.after !== null ? <div className="grid gap-2 sm:grid-cols-2"><TimelineValue label="Before" value={event.before} /><TimelineValue label="After" value={event.after} /></div> : null}</li>)}</ol> : <p className="rounded-md border border-dashed p-4 text-sm text-muted-foreground">No operational events have been recorded for this mission yet.</p>}</CardContent></Card>;
}

function TimelineValue({ label, value }: { label: string; value: unknown }) { return <div className="min-w-0 rounded-md bg-muted/40 p-3"><p className="text-xs font-bold text-muted-foreground">{label}</p>{isRecord(value) ? <dl className="mt-2 grid gap-2 text-sm">{Object.entries(value).map(([key, item]) => <div key={key}><dt className="font-semibold text-muted-foreground">{readableKey(key)}</dt><dd className="break-words">{readableValue(item)}</dd></div>)}</dl> : <p className="mt-1 break-words text-sm">{readableValue(value)}</p>}</div>; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function readableKey(key: string) { return key.replace(/([A-Z])/g, " $1").replace(/[_-]/g, " ").replace(/^./, (letter) => letter.toUpperCase()); }
function readableValue(value: unknown): string { if (value === null || value === undefined) return "Not recorded"; if (typeof value === "boolean") return value ? "Yes" : "No"; if (Array.isArray(value)) return value.map(readableValue).join(", "); if (isRecord(value)) return Object.entries(value).map(([key, item]) => `${readableKey(key)}: ${readableValue(item)}`).join(" · "); return String(value); }
function eventLabel(type: string) { return type.split(/[_.-]/).filter(Boolean).map((word) => word[0]?.toUpperCase() + word.slice(1).toLowerCase()).join(" ") || "Mission updated"; }

function DangerZone({ deleting, onDelete }: Pick<Props, "deleting" | "onDelete">) {
  return <section className="flex flex-col gap-4 rounded-lg border border-destructive/30 bg-destructive/5 p-5 sm:flex-row sm:items-center sm:justify-between" aria-labelledby="danger-zone-heading"><div><h2 id="danger-zone-heading" className="font-extrabold text-destructive">Delete mission</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Permanently remove this mission, its plan, schedule, and recorded outcome.</p></div><Button type="button" variant="danger" className="w-full sm:w-auto" onClick={onDelete} isLoading={deleting} loadingLabel="Deleting mission">Delete mission</Button></section>;
}

function LifecycleCard({ mission, currentStep, action, onAdvance, onReport, onOpenCloseout }: Pick<Props, "mission" | "action" | "onAdvance"> & { currentStep?: MissionStep; onReport: (type: OperationalReportType) => void; onOpenCloseout: () => void }) {
  const actionForStage = nextAction(mission, currentStep);
  return <Card variant="highlight"><CardHeader><CardTitle>Mission progress</CardTitle><CardDescription>Complete the approved batches in order. You may record the current batch early; its schedule remains unchanged.</CardDescription></CardHeader><CardContent className="grid gap-5"><ol className="grid gap-3 sm:grid-cols-3">{(["WAITING", "HARVESTING", "DRYING"] as const).map((stage) => <li key={stage} className={`flex items-center gap-3 rounded-md border p-3 ${stage === mission.stage ? "border-primary bg-primary/5" : isPastStage(mission.stage, stage) ? "border-leaf-300 bg-leaf-100/50" : "bg-card"}`}>{isPastStage(mission.stage, stage) ? <CheckCircle2 className="h-5 w-5 text-success-foreground" aria-hidden="true" /> : <Circle className="h-5 w-5 text-muted-foreground" aria-hidden="true" />}<span className="font-bold">{stage === "WAITING" ? "Waiting" : stage === "HARVESTING" ? "Harvesting" : "Drying"}</span></li>)}</ol>
    {currentStep ? <div className="rounded-md border border-primary/30 bg-card p-4"><p className="text-sm font-semibold text-primary">Current batch</p><h3 className="mt-1 text-lg font-extrabold">{currentStep.title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{currentStep.description}</p><p className="mt-3 flex items-center gap-1.5 text-sm font-semibold"><CalendarDays className="h-4 w-4 text-primary" aria-hidden="true" />{formatStepSchedule(currentStep)}</p></div> : <p className="rounded-md border bg-card p-4 text-sm leading-6 text-muted-foreground">{mission.status === "COMPLETED" ? "This mission is complete." : mission.status === "CLOSEOUT" ? "Record the real outcome, then confirm it to complete this mission." : mission.stage === "FINISHED" ? "All scheduled batches are complete. Start closeout when you are ready to record the result." : "Start the next stage when you are ready."}</p>}
    {mission.status === "CLOSEOUT" ? <Button type="button" className="justify-self-end" icon={<ClipboardCheck aria-hidden="true" />} onClick={onOpenCloseout}>{mission.closeout ? "Review closeout" : "Close out mission"}</Button> : actionForStage ? <Button type="button" className="justify-self-end" icon={actionForStage.kind === "report" ? <ClipboardCheck aria-hidden="true" /> : <Play aria-hidden="true" />} isLoading={action === actionForStage.id} loadingLabel={actionForStage.label} onClick={() => actionForStage.kind === "report" ? onReport(actionForStage.reportType) : onAdvance(actionForStage.id as AdvanceStage)}>{actionForStage.label}</Button> : null}
  </CardContent></Card>;
}

function ScheduleCard({ steps, currentStepId }: { steps: MissionStep[]; currentStepId?: string }) {
  return <Card><CardHeader><CardTitle>Approved schedule</CardTitle><CardDescription>Only the next scheduled batch can be completed.</CardDescription></CardHeader><CardContent className="grid gap-3">{steps.length ? steps.map((step) => <article key={step.missionStepId} className={`grid gap-3 rounded-md border p-4 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-start ${step.missionStepId === currentStepId ? "border-primary/40 bg-primary/5" : ""}`}><span className="grid h-8 w-8 place-items-center rounded-full bg-primary/10 text-sm font-extrabold text-primary">{step.sequence}</span><div><h3 className="font-bold">{step.title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{step.description}</p><p className="mt-2 flex items-center gap-1.5 text-sm font-semibold"><CalendarDays className="h-4 w-4 text-primary" aria-hidden="true" />{formatStepSchedule(step)}</p></div><Badge variant={step.status === "COMPLETED" ? "success" : step.missionStepId === currentStepId ? "info" : "neutral"}>{step.status === "COMPLETED" ? "Completed" : step.missionStepId === currentStepId ? "Current batch" : "Scheduled"}</Badge></article>) : <p className="text-sm leading-6 text-muted-foreground">No schedule steps are available for this mission.</p>}</CardContent></Card>;
}

function CloseoutForm({ mission, saving, onSave }: { mission: Mission; saving: boolean; onSave: (values: MissionCloseoutInput) => void }) {
  const plannedHarvestKg = plannedMetric(mission, "plannedHarvestKg"); const plannedDriedKg = plannedMetric(mission, "plannedDriedKg");
  const [values, setValues] = useState({ actualHarvestKg: "", actualDriedKg: "", harvestedAreaHectares: "", dryingCompleted: "yes", rejectedKg: "", notes: "" });
  const set = (key: keyof typeof values, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const optional = (value: string) => value === "" ? null : Number(value);
  return <Card variant="highlight"><CardHeader><CardTitle>Close out this mission</CardTitle><CardDescription>Compare the planned outcome with what happened in the field. This is saved for future mission context.</CardDescription></CardHeader><CardContent><form className="grid gap-5" onSubmit={(event) => { event.preventDefault(); onSave({ actualHarvestKg: Number(values.actualHarvestKg), actualDriedKg: Number(values.actualDriedKg), harvestedAreaHectares: optional(values.harvestedAreaHectares), dryingCompleted: values.dryingCompleted === "yes", rejectedKg: optional(values.rejectedKg), notes: values.notes.trim() || null }); }}><div className="grid gap-3 rounded-md border bg-card p-4 sm:grid-cols-2"><Metric label="Planned harvest" value={plannedHarvestKg} /><Metric label="Planned dried output" value={plannedDriedKg} /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Actual harvest (kg)" value={values.actualHarvestKg} onChange={(value) => set("actualHarvestKg", value)} required /><Field label="Actual dried output (kg)" value={values.actualDriedKg} onChange={(value) => set("actualDriedKg", value)} required /><Field label="Harvested area (hectares)" value={values.harvestedAreaHectares} onChange={(value) => set("harvestedAreaHectares", value)} /><Field label="Rejected or damaged (kg)" value={values.rejectedKg} onChange={(value) => set("rejectedKg", value)} /></div><Decision label="Was drying completed?" value={values.dryingCompleted} onChange={(value) => set("dryingCompleted", value)} /><label className="grid gap-2 text-sm font-semibold">Problems or deviations <span className="font-normal text-muted-foreground">Optional</span><Textarea value={values.notes} onChange={(event) => set("notes", event.target.value)} placeholder="Rain, worker availability, lower yield, or other harvest notes…" /></label><Button type="submit" className="justify-self-end" isLoading={saving} loadingLabel="Saving closeout">Save closeout for review</Button></form></CardContent></Card>;
}

function CloseoutCard({ mission, confirming, onConfirm }: { mission: Mission; confirming: boolean; onConfirm: () => void }) {
  const closeout = mission.closeout!;
  return <Card variant="success"><CardHeader><CardTitle>Closeout ready for confirmation</CardTitle><CardDescription>Review the farmer-recorded result, then complete the mission.</CardDescription></CardHeader><CardContent className="grid gap-4"><dl className="grid gap-3 sm:grid-cols-2"><Metric label="Planned harvest" value={closeout.plannedHarvestKg} /><Metric label="Actual harvest" value={closeout.actualHarvestKg} /><Metric label="Planned dried output" value={closeout.plannedDriedKg} /><Metric label="Actual dried output" value={closeout.actualDriedKg} /></dl><div className="grid gap-2 rounded-md border bg-card p-4 text-sm leading-6"><p><span className="font-bold">Harvest difference: </span>{difference(closeout.actualHarvestKg, closeout.plannedHarvestKg)} kg</p><p><span className="font-bold">Dried-output difference: </span>{difference(closeout.actualDriedKg, closeout.plannedDriedKg)} kg</p></div><div className="grid gap-2 border-t pt-4 text-sm leading-6"><p><span className="font-bold">Drying: </span>{closeout.dryingCompleted ? "Completed" : "Not completed"}</p>{closeout.harvestedAreaHectares !== null ? <p><span className="font-bold">Harvested area: </span>{closeout.harvestedAreaHectares.toLocaleString("en-ID")} ha</p> : null}{closeout.rejectedKg !== null ? <p><span className="font-bold">Rejected or damaged: </span>{closeout.rejectedKg.toLocaleString("en-ID")} kg</p> : null}{closeout.notes ? <p><span className="font-bold">Deviations: </span>{closeout.notes}</p> : null}</div><Button type="button" className="w-full sm:w-fit" icon={<CheckCircle2 aria-hidden="true" />} isLoading={confirming} loadingLabel="Confirming closeout" onClick={onConfirm}>Confirm and complete mission</Button></CardContent></Card>;
}

function Field({ label, value, onChange, required = false }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label className="grid gap-2 text-sm font-semibold">{label}{required ? <span aria-hidden="true"> *</span> : null}<Input type="number" min="0" step="any" required={required} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Decision({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <fieldset className="grid gap-2"><legend className="text-sm font-semibold">{label}</legend><div className="flex gap-4"><label className="flex min-h-11 items-center gap-2 text-sm"><input type="radio" name={label} value="yes" checked={value === "yes"} onChange={(event) => onChange(event.target.value)} />Yes</label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="radio" name={label} value="no" checked={value === "no"} onChange={(event) => onChange(event.target.value)} />No</label></div></fieldset>; }
function Metric({ label, value }: { label: string; value: number | null }) { return <div><dt className="text-sm font-semibold text-muted-foreground">{label}</dt><dd className="mt-1 text-xl font-extrabold tabular-nums">{value === null ? "Not recorded" : `${value.toLocaleString("en-ID")} kg`}</dd></div>; }
function plannedMetric(mission: Mission, key: "plannedHarvestKg" | "plannedDriedKg") { const value = mission.constraints.find((item) => item.key === key)?.value; return typeof value === "number" ? value : null; }
function difference(actual: number, planned: number) { return `${actual - planned >= 0 ? "+" : ""}${(actual - planned).toLocaleString("en-ID")}`; }
function isPastStage(current: MissionStage, stage: "WAITING" | "HARVESTING" | "DRYING") { return ["WAITING", "HARVESTING", "DRYING", "FINISHED", "TO_REVIEW", "COMPLETED"].indexOf(current) > ["WAITING", "HARVESTING", "DRYING"].indexOf(stage); }
function nextAction(mission: Mission, currentStep?: MissionStep) { if (mission.status !== "ACTIVE") return null; if (mission.stage === "WAITING") return { kind: "stage" as const, id: "HARVESTING", label: "Start harvesting" }; if (currentStep) return { kind: "report" as const, id: currentStep.missionStepId, reportType: currentStep.status === "IN_PROGRESS" ? "ACTIVITY_COMPLETED" as const : "ACTIVITY_STARTED" as const, label: currentStep.status === "IN_PROGRESS" ? "Complete current task" : "Start current task" }; if (mission.stage === "HARVESTING") return { kind: "stage" as const, id: "DRYING", label: "Start drying" }; if (mission.stage === "DRYING") return { kind: "stage" as const, id: "FINISHED", label: "Finish execution" }; if (mission.stage === "FINISHED") return { kind: "stage" as const, id: "TO_REVIEW", label: "Close out" }; return null; }
function PlanCard({ plan }: { plan: NonNullable<ReturnType<typeof missionPlan>> }) { return <Card variant="highlight"><CardHeader><div className="flex flex-wrap items-center gap-2"><CardTitle>Approved plan</CardTitle>{plan.recommended ? <Badge variant="ai"><ClipboardList aria-hidden="true" />TUNAS recommendation</Badge> : null}</div><CardDescription>{plan.summary}</CardDescription></CardHeader><CardContent className="grid gap-4">{plan.assumptions.length ? <Section label="Assumptions" values={plan.assumptions} /> : null}{Object.keys(plan.risks).length ? <div className="rounded-md border border-harvest-300 bg-harvest-100/50 p-4"><p className="flex items-center gap-2 font-bold text-harvest-700"><ShieldAlert className="h-4 w-4" aria-hidden="true" />Risks to review</p><ul className="mt-2 grid gap-1 text-sm leading-6 text-ink-700">{Object.entries(plan.risks).map(([risk, reason]) => <li key={risk}><span className="font-semibold">{risk}: </span>{reason}</li>)}</ul></div> : null}<p className="text-sm leading-6 text-muted-foreground">Drying estimate: {plan.dryingEstimateDays} days. {plan.dryingEstimateReason}</p></CardContent></Card>; }
function Section({ label, values }: { label: string; values: string[] }) { return <div><p className="font-bold">{label}</p><ul className="mt-2 grid gap-1 text-sm leading-6 text-muted-foreground">{values.map((value, index) => <li key={`${index}-${value}`}>• {value}</li>)}</ul></div>; }
