import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, CheckCircle2, Circle, ClipboardCheck, ClipboardList, Play, ShieldAlert, Sprout } from "lucide-react";
import { Link } from "react-router";
import type { Mission, MissionCloseoutInput, MissionStage, MissionStep } from "@/api/missions";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/Card";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/PageHeader";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { formatStepSchedule, missionPlan, StageBadge, StatusBadge } from "./MissionsView";

type AdvanceStage = "HARVESTING" | "DRYING" | "FINISHED" | "TO_REVIEW";
type Props = { mission: Mission; onDelete: () => void; deleting: boolean; action: string | null; onAdvance: (stage: AdvanceStage) => void; onCompleteStep: (stepId: string) => void; onSaveCloseout: (values: MissionCloseoutInput) => void; onConfirmCloseout: () => void };

export function MissionDetailView({ mission, onDelete, deleting, action, onAdvance, onCompleteStep, onSaveCloseout, onConfirmCloseout }: Props) {
  const plan = missionPlan(mission);
  const batches = mission.cropBatches.map((item) => item.cropBatch.variety || "Shallot batch");
  const currentStep = ["HARVESTING", "DRYING"].includes(mission.stage) ? mission.missionSteps.find((step) => step.stage === mission.stage && step.status !== "COMPLETED") : undefined;
  const [closeoutOpen, setCloseoutOpen] = useState(mission.status === "CLOSEOUT");
  useEffect(() => { setCloseoutOpen(mission.status === "CLOSEOUT"); }, [mission.status]);
  return <div className="grid gap-6"><PageHeader eyebrow="Mission details" title="Harvest mission" description={mission.originalMessage} badges={<><StatusBadge status={mission.status} /><StageBadge stage={mission.stage} /></>} actions={<div className="flex w-full flex-wrap justify-end gap-2 sm:w-auto"><Button asChild type="button" variant="outline" icon={<ArrowLeft aria-hidden="true" />}><Link to="/missions">All missions</Link></Button>{mission.closeout ? <Button type="button" variant="secondary" icon={<ClipboardCheck aria-hidden="true" />} onClick={() => setCloseoutOpen(true)}>View closeout</Button> : null}<Button type="button" variant="danger" onClick={onDelete} isLoading={deleting} loadingLabel="Deleting mission">Delete mission</Button></div>} />
    <div className="grid gap-6"><LifecycleCard mission={mission} currentStep={currentStep} action={action} onAdvance={onAdvance} onCompleteStep={onCompleteStep} onOpenCloseout={() => setCloseoutOpen(true)} />
      <Card><CardHeader><CardTitle>Mission context</CardTitle><CardDescription>Farmer request and crop batches included in this mission.</CardDescription></CardHeader><CardContent className="grid gap-4"><div><p className="text-sm font-semibold text-muted-foreground">Farmer request</p><p className="mt-1 leading-7">{mission.originalMessage}</p></div>{batches.length ? <div className="border-t pt-4"><p className="text-sm font-semibold text-muted-foreground">Crop batches</p><div className="mt-2 flex flex-wrap gap-2">{batches.map((batch, index) => <Badge key={`${batch}-${index}`} variant="source"><Sprout aria-hidden="true" />{batch}</Badge>)}</div></div> : null}{mission.notes ? <div className="border-t pt-4"><p className="text-sm font-semibold text-muted-foreground">Notes</p><p className="mt-1 leading-7">{mission.notes}</p></div> : null}</CardContent></Card>
      {plan ? <PlanCard plan={plan} /> : null}
      <ScheduleCard steps={mission.missionSteps} currentStepId={currentStep?.missionStepId} />
    </div><Dialog open={closeoutOpen} onOpenChange={setCloseoutOpen}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>{mission.closeout ? "Review closeout" : "Close out this mission"}</DialogTitle><DialogDescription>{mission.closeout ? "Review the recorded outcome before completing the mission." : "Compare the planned outcome with what happened in the field."}</DialogDescription></DialogHeader>{mission.closeout ? <CloseoutCard mission={mission} confirming={action === "confirm-closeout"} onConfirm={onConfirmCloseout} /> : <CloseoutForm mission={mission} saving={action === "closeout"} onSave={onSaveCloseout} />}</DialogContent></Dialog></div>;
}

function LifecycleCard({ mission, currentStep, action, onAdvance, onCompleteStep, onOpenCloseout }: Pick<Props, "mission" | "action" | "onAdvance" | "onCompleteStep"> & { currentStep?: MissionStep; onOpenCloseout: () => void }) {
  const actionForStage = nextAction(mission, currentStep);
  return <Card variant="highlight"><CardHeader><CardTitle>Mission progress</CardTitle><CardDescription>Complete the approved batches in order. You may record the current batch early; its schedule remains unchanged.</CardDescription></CardHeader><CardContent className="grid gap-5"><ol className="grid gap-3 sm:grid-cols-3">{(["WAITING", "HARVESTING", "DRYING"] as const).map((stage) => <li key={stage} className={`flex items-center gap-3 rounded-md border p-3 ${stage === mission.stage ? "border-primary bg-primary/5" : isPastStage(mission.stage, stage) ? "border-leaf-300 bg-leaf-100/50" : "bg-card"}`}>{isPastStage(mission.stage, stage) ? <CheckCircle2 className="h-5 w-5 text-success-foreground" aria-hidden="true" /> : <Circle className="h-5 w-5 text-muted-foreground" aria-hidden="true" />}<span className="font-bold">{stage === "WAITING" ? "Waiting" : stage === "HARVESTING" ? "Harvesting" : "Drying"}</span></li>)}</ol>
    {currentStep ? <div className="rounded-md border border-primary/30 bg-card p-4"><p className="text-sm font-semibold text-primary">Current batch</p><h3 className="mt-1 text-lg font-extrabold">{currentStep.title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{currentStep.description}</p><p className="mt-3 flex items-center gap-1.5 text-sm font-semibold"><CalendarDays className="h-4 w-4 text-primary" aria-hidden="true" />{formatStepSchedule(currentStep)}</p></div> : <p className="rounded-md border bg-card p-4 text-sm leading-6 text-muted-foreground">{mission.status === "COMPLETED" ? "This mission is complete." : mission.status === "CLOSEOUT" ? "Record the real outcome, then confirm it to complete this mission." : mission.stage === "FINISHED" ? "All scheduled batches are complete. Start closeout when you are ready to record the result." : "Start the next stage when you are ready."}</p>}
    {mission.status === "CLOSEOUT" ? <Button type="button" className="justify-self-end" icon={<ClipboardCheck aria-hidden="true" />} onClick={onOpenCloseout}>{mission.closeout ? "Review closeout" : "Record closeout"}</Button> : actionForStage ? <Button type="button" className="justify-self-end" icon={actionForStage.kind === "step" ? <ClipboardCheck aria-hidden="true" /> : <Play aria-hidden="true" />} isLoading={action === actionForStage.id} loadingLabel={actionForStage.label} onClick={() => actionForStage.kind === "step" ? onCompleteStep(actionForStage.id) : onAdvance(actionForStage.id as AdvanceStage)}>{actionForStage.label}</Button> : null}
  </CardContent></Card>;
}

function ScheduleCard({ steps, currentStepId }: { steps: MissionStep[]; currentStepId?: string }) {
  return <Card><CardHeader><CardTitle>Approved schedule</CardTitle><CardDescription>Only the next scheduled batch can be completed.</CardDescription></CardHeader><CardContent className="grid gap-3">{steps.length ? steps.map((step) => <article key={step.missionStepId} className={`grid gap-3 rounded-md border p-4 sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-start ${step.missionStepId === currentStepId ? "border-primary/40 bg-primary/5" : ""}`}><span className="grid h-8 w-8 place-items-center rounded-full bg-primary/10 text-sm font-extrabold text-primary">{step.sequence}</span><div><h3 className="font-bold">{step.title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{step.description}</p><p className="mt-2 flex items-center gap-1.5 text-sm font-semibold"><CalendarDays className="h-4 w-4 text-primary" aria-hidden="true" />{formatStepSchedule(step)}</p></div><Badge variant={step.status === "COMPLETED" ? "success" : step.missionStepId === currentStepId ? "info" : "neutral"}>{step.status === "COMPLETED" ? "Completed" : step.missionStepId === currentStepId ? "Current batch" : "Scheduled"}</Badge></article>) : <p className="text-sm leading-6 text-muted-foreground">No schedule steps are available for this mission.</p>}</CardContent></Card>;
}

function CloseoutForm({ mission, saving, onSave }: { mission: Mission; saving: boolean; onSave: (values: MissionCloseoutInput) => void }) {
  const plannedHarvestKg = plannedMetric(mission, "plannedHarvestKg"); const plannedDriedKg = plannedMetric(mission, "plannedDriedKg");
  const [values, setValues] = useState({ actualHarvestKg: "", actualDriedKg: "", harvestedAreaHectares: "", buyerTargetMet: "yes", dryingCompleted: "yes", rejectedKg: "", notes: "" });
  const set = (key: keyof typeof values, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const optional = (value: string) => value === "" ? null : Number(value);
  return <Card variant="highlight"><CardHeader><CardTitle>Close out this mission</CardTitle><CardDescription>Compare the planned outcome with what happened in the field. This is saved for future mission context.</CardDescription></CardHeader><CardContent><form className="grid gap-5" onSubmit={(event) => { event.preventDefault(); onSave({ actualHarvestKg: Number(values.actualHarvestKg), actualDriedKg: Number(values.actualDriedKg), harvestedAreaHectares: optional(values.harvestedAreaHectares), buyerTargetMet: values.buyerTargetMet === "yes", dryingCompleted: values.dryingCompleted === "yes", rejectedKg: optional(values.rejectedKg), notes: values.notes.trim() || null }); }}><div className="grid gap-3 rounded-md border bg-card p-4 sm:grid-cols-2"><Metric label="Planned harvest" value={plannedHarvestKg} /><Metric label="Planned dried output" value={plannedDriedKg} /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Actual harvest (kg)" value={values.actualHarvestKg} onChange={(value) => set("actualHarvestKg", value)} required /><Field label="Actual dried output (kg)" value={values.actualDriedKg} onChange={(value) => set("actualDriedKg", value)} required /><Field label="Harvested area (hectares)" value={values.harvestedAreaHectares} onChange={(value) => set("harvestedAreaHectares", value)} /><Field label="Rejected or damaged (kg)" value={values.rejectedKg} onChange={(value) => set("rejectedKg", value)} /></div><div className="grid gap-4 sm:grid-cols-2"><Decision label="Was the buyer target met?" value={values.buyerTargetMet} onChange={(value) => set("buyerTargetMet", value)} /><Decision label="Was drying completed?" value={values.dryingCompleted} onChange={(value) => set("dryingCompleted", value)} /></div><label className="grid gap-2 text-sm font-semibold">Problems or deviations <span className="font-normal text-muted-foreground">Optional</span><Textarea value={values.notes} onChange={(event) => set("notes", event.target.value)} placeholder="Rain, worker availability, lower yield, buyer changes…" /></label><Button type="submit" className="justify-self-end" isLoading={saving} loadingLabel="Saving closeout">Save closeout for review</Button></form></CardContent></Card>;
}

function CloseoutCard({ mission, confirming, onConfirm }: { mission: Mission; confirming: boolean; onConfirm: () => void }) {
  const closeout = mission.closeout!;
  return <Card variant="success"><CardHeader><CardTitle>Closeout ready for confirmation</CardTitle><CardDescription>Review the farmer-recorded result, then complete the mission.</CardDescription></CardHeader><CardContent className="grid gap-4"><dl className="grid gap-3 sm:grid-cols-2"><Metric label="Planned harvest" value={closeout.plannedHarvestKg} /><Metric label="Actual harvest" value={closeout.actualHarvestKg} /><Metric label="Planned dried output" value={closeout.plannedDriedKg} /><Metric label="Actual dried output" value={closeout.actualDriedKg} /></dl><div className="grid gap-2 rounded-md border bg-card p-4 text-sm leading-6"><p><span className="font-bold">Harvest difference: </span>{difference(closeout.actualHarvestKg, closeout.plannedHarvestKg)} kg</p><p><span className="font-bold">Dried-output difference: </span>{difference(closeout.actualDriedKg, closeout.plannedDriedKg)} kg</p></div><div className="grid gap-2 border-t pt-4 text-sm leading-6"><p><span className="font-bold">Buyer target: </span>{closeout.buyerTargetMet ? "Met" : "Not met"}</p><p><span className="font-bold">Drying: </span>{closeout.dryingCompleted ? "Completed" : "Not completed"}</p>{closeout.harvestedAreaHectares !== null ? <p><span className="font-bold">Harvested area: </span>{closeout.harvestedAreaHectares.toLocaleString("en-ID")} ha</p> : null}{closeout.rejectedKg !== null ? <p><span className="font-bold">Rejected or damaged: </span>{closeout.rejectedKg.toLocaleString("en-ID")} kg</p> : null}{closeout.notes ? <p><span className="font-bold">Deviations: </span>{closeout.notes}</p> : null}</div><Button type="button" className="w-full sm:w-fit" icon={<CheckCircle2 aria-hidden="true" />} isLoading={confirming} loadingLabel="Confirming closeout" onClick={onConfirm}>Confirm and complete mission</Button></CardContent></Card>;
}

function Field({ label, value, onChange, required = false }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label className="grid gap-2 text-sm font-semibold">{label}{required ? <span aria-hidden="true"> *</span> : null}<Input type="number" min="0" step="any" required={required} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Decision({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <fieldset className="grid gap-2"><legend className="text-sm font-semibold">{label}</legend><div className="flex gap-4"><label className="flex min-h-11 items-center gap-2 text-sm"><input type="radio" name={label} value="yes" checked={value === "yes"} onChange={(event) => onChange(event.target.value)} />Yes</label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="radio" name={label} value="no" checked={value === "no"} onChange={(event) => onChange(event.target.value)} />No</label></div></fieldset>; }
function Metric({ label, value }: { label: string; value: number | null }) { return <div><dt className="text-sm font-semibold text-muted-foreground">{label}</dt><dd className="mt-1 text-xl font-extrabold tabular-nums">{value === null ? "Not recorded" : `${value.toLocaleString("en-ID")} kg`}</dd></div>; }
function plannedMetric(mission: Mission, key: "plannedHarvestKg" | "plannedDriedKg") { const value = mission.constraints.find((item) => item.key === key)?.value; return typeof value === "number" ? value : null; }
function difference(actual: number, planned: number) { return `${actual - planned >= 0 ? "+" : ""}${(actual - planned).toLocaleString("en-ID")}`; }
function isPastStage(current: MissionStage, stage: "WAITING" | "HARVESTING" | "DRYING") { return ["WAITING", "HARVESTING", "DRYING", "FINISHED", "TO_REVIEW", "COMPLETED"].indexOf(current) > ["WAITING", "HARVESTING", "DRYING"].indexOf(stage); }
function nextAction(mission: Mission, currentStep?: MissionStep) { if (mission.status !== "ACTIVE") return null; if (mission.stage === "WAITING") return { kind: "stage" as const, id: "HARVESTING", label: "Start harvesting" }; if (currentStep) return { kind: "step" as const, id: currentStep.missionStepId, label: "Mark batch complete" }; if (mission.stage === "HARVESTING") return { kind: "stage" as const, id: "DRYING", label: "Start drying" }; if (mission.stage === "DRYING") return { kind: "stage" as const, id: "FINISHED", label: "Finish execution" }; if (mission.stage === "FINISHED") return { kind: "stage" as const, id: "TO_REVIEW", label: "Start closeout" }; return null; }
function PlanCard({ plan }: { plan: NonNullable<ReturnType<typeof missionPlan>> }) { return <Card variant="highlight"><CardHeader><div className="flex flex-wrap items-center gap-2"><CardTitle>Approved plan</CardTitle>{plan.recommended ? <Badge variant="ai"><ClipboardList aria-hidden="true" />TUNAS recommendation</Badge> : null}</div><CardDescription>{plan.summary}</CardDescription></CardHeader><CardContent className="grid gap-4">{plan.assumptions.length ? <Section label="Assumptions" values={plan.assumptions} /> : null}{Object.keys(plan.risks).length ? <div className="rounded-md border border-harvest-300 bg-harvest-100/50 p-4"><p className="flex items-center gap-2 font-bold text-harvest-700"><ShieldAlert className="h-4 w-4" aria-hidden="true" />Risks to review</p><ul className="mt-2 grid gap-1 text-sm leading-6 text-ink-700">{Object.entries(plan.risks).map(([risk, reason]) => <li key={risk}><span className="font-semibold">{risk}: </span>{reason}</li>)}</ul></div> : null}<p className="text-sm leading-6 text-muted-foreground">Drying estimate: {plan.dryingEstimateDays} days. {plan.dryingEstimateReason}</p></CardContent></Card>; }
function Section({ label, values }: { label: string; values: string[] }) { return <div><p className="font-bold">{label}</p><ul className="mt-2 grid gap-1 text-sm leading-6 text-muted-foreground">{values.map((value) => <li key={value}>• {value}</li>)}</ul></div>; }
