import { FileText, Sparkles } from "lucide-react";
import type { MissionPlanRecommendation, MissionPreviewPlan } from "@/api/missions";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/Card";

export function MissionCandidateReview({ plans, recommendation, selectedPlan, onSelect, onApprove }: { plans: MissionPreviewPlan[]; recommendation: MissionPlanRecommendation | null; selectedPlan: MissionPreviewPlan | null; onSelect: (planId: string) => void; onApprove: () => void }) {
  const ordered = [...plans].sort((a, b) => Number(b.planId === recommendation?.planId) - Number(a.planId === recommendation?.planId));
  return <div className="grid gap-4">{ordered.map((plan) => {
    const recommended = plan.planId === recommendation?.planId;
    return <Card key={plan.planId} variant={recommended ? "highlight" : "default"}><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle>{plan.name}</CardTitle>{recommended ? <Badge variant="ai"><Sparkles aria-hidden="true" />TUNAS recommendation</Badge> : null}{plan.weatherStatus === "WEATHER_UNVERIFIED" ? <Badge variant="warning">Weather recheck required</Badge> : null}</div><CardDescription>{plan.summary}</CardDescription></CardHeader><CardContent className="grid gap-5"><CandidateTimeline activities={plan.activities} /><TextSection title="Recommendation reasons" values={recommended ? recommendation?.reasons.map((reason) => reason.text) ?? [] : []} /><EvidenceSection evidence={plan.evidence} /><TextSection title="Assumptions" values={plan.assumptions} /><TextSection title="Tradeoffs" values={plan.tradeoffs} /><TextSection title="Risks" values={Object.entries(plan.risks).map(([risk, detail]) => `${risk}: ${detail}`)} /><section><h4 className="font-bold">Drying guidance window</h4><p className="text-sm leading-6 text-muted-foreground">{plan.dryingEstimateMinDays}–{plan.dryingEstimateMaxDays} days. {plan.dryingEstimateReason}</p></section></CardContent><CardFooter className="justify-end"><Button type="button" variant={selectedPlan?.planId === plan.planId ? "primary" : "outline"} onClick={() => onSelect(plan.planId)}>{selectedPlan?.planId === plan.planId ? "Selected" : "Select this plan"}</Button></CardFooter></Card>;
  })}<Card variant="success"><CardHeader><CardTitle>No schedule is applied before approval</CardTitle><CardDescription>Selecting a candidate only prepares it for explicit approval.</CardDescription></CardHeader><CardFooter className="justify-end"><Button type="button" size="lg" disabled={!selectedPlan} onClick={onApprove} icon={<FileText aria-hidden="true" />}>Review and approve selected plan</Button></CardFooter></Card></div>;
}

function CandidateTimeline({ activities }: { activities: MissionPreviewPlan["activities"] }) {
  const groups = [...activities].sort((a, b) => a.startsOn.localeCompare(b.startsOn)).reduce((result, activity) => result.set(activity.startsOn.slice(0, 10), [...(result.get(activity.startsOn.slice(0, 10)) ?? []), activity]), new Map<string, MissionPreviewPlan["activities"]>());
  return <section className="grid gap-3"><h4 className="font-bold">Candidate timeline</h4>{[...groups].map(([date, items]) => <div key={date} className="grid gap-2"><h5 className="text-sm font-bold text-primary">{new Intl.DateTimeFormat("id-ID", { dateStyle: "full", timeZone: items[0]?.timezone }).format(new Date(`${date}T00:00:00`))}</h5><ol className="grid gap-2 border-l-2 border-primary/20 pl-4">{items.map((activity, index) => <li key={`${activity.actionKind}-${activity.startsOn}-${index}`} className="grid gap-1 rounded-md bg-muted/30 p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{activity.title}</strong><span className="text-sm font-semibold">{activityTime(activity)}</span></div><p className="text-sm leading-6 text-muted-foreground">{activity.description}</p><p className="text-xs text-muted-foreground">{[activity.targetHarvestKg != null ? `Target ${activity.targetHarvestKg} kg` : null, activity.workers != null ? `${activity.workers} workers` : null, activity.isConditional ? "Conditional" : null].filter(Boolean).join(" · ")}</p></li>)}</ol></div>)}</section>;
}

function activityTime(activity: MissionPreviewPlan["activities"][number]) {
  if (activity.scheduleType === "DAILY_WINDOW" && activity.windowStart && activity.windowEnd) return `${activity.windowStart}–${activity.windowEnd}`;
  return activity.scheduleType === "CONDITION_GATE" ? "Farmer-confirmed condition gate" : `${activity.startsOn.slice(0, 10)}–${activity.endsOn.slice(0, 10)}`;
}

function TextSection({ title, values }: { title: string; values: string[] }) { return <section><h4 className="font-bold">{title}</h4>{values.length ? <ul className="mt-1 grid gap-1 text-sm leading-6 text-muted-foreground">{values.map((value) => <li key={value}>• {value}</li>)}</ul> : <p className="mt-1 text-sm text-muted-foreground">None supplied.</p>}</section>; }
function EvidenceSection({ evidence }: { evidence: MissionPreviewPlan["evidence"] }) { return <section><h4 className="font-bold">Deterministic evidence</h4>{evidence.length ? <dl className="mt-1 grid gap-2 text-sm">{evidence.map((item) => <div key={item.evidenceId} className="rounded-md bg-muted/30 p-2"><dt className="font-semibold">{item.passed ? "Pass" : "Fail"} · {item.rule}</dt><dd className="break-words text-muted-foreground">{item.source}: {String(item.value)}</dd></div>)}</dl> : <p className="mt-1 text-sm text-muted-foreground">None supplied.</p>}</section>; }
